# Setup
title:               Alden's Blog
tagline:             ''
description:         'A little bit of learning is a dangerous thing...'                       # Comes up in sidebar
url:                 http://blog.aldenkane.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Alden Kane
  url:               https://aldenkane.com
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
